# Generated by Django 4.0.3 on 2022-04-17 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='author',
            new_name='user',
        ),
    ]
